---
#title: "01_About"
output:
  html_document:
    df_print: paged
  pdf_document:
    theme: hpstr
    highlight: github
---
# MAPLE Overview

MAPLE is a summary statistics-based MR method that utilizes a set of correlated instrumental SNPs and self-adaptively determines the sample structure as well as multiple pleiotropic effects, both of which are commonly encountered in MR analysis. MAPLE can be used straightforward regardless of the proportion of sample overlap between the exposure GWAS and the outcome GWAS. MAPLE first accurately estimate the error matrix parameter using data from genome-wide summary statistics, then places the inference of the causal effect into a likelihood framework, accompanied by a scalable sampling-based algorithm to obtain calibrated p-values. With extensive simulations and real applications, we have illustrated MAPLE can control type I error, boost power, obtain accurate estimates, and is robust against reverse causality and model misspecifications. The software is distributed under the MIT License.

# Contact

If you have questions, feel free to leave messages on the [github issues](https://github.com/yuanzhongshang/MAPLE/issues) or contact us through email: <yuanzhongshang@sdu.edu.cn>.