remote_theme: allejo/jekyll-docs-theme
name: MAPLE

project:
  version: 1.0.0
  download_url: https://github.com/yuanzhongshang/MAPLE/
  download_text: Download

license:
  software: GNU License 3.0
  software_url: https://www.gnu.org/licenses/licenses.en.html
 
links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/yuanzhongshang/MAPLE/
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/yuanzhongshang/MAPLE/
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/yuanzhongshang/MAPLE/
    - title: Issues
      icon: bug
      url: https://github.com/yuanzhongshang/MAPLE/issues?state=open

ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#8497B0"
    light: "#E49690"
  border_color:
    dark: "#8497B0"
    light: "#E49690"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#8497B0"
    light:
      color1: "#E49690"
      color2: "#8497B0"
  masthead:
    color:
      dark: "#fff"
      light: "#666666"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: yuanzhongshang
    repo: MAPLE
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - LICENSE.md
  - README.md
