// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MAPLE_CPP
SEXP MAPLE_CPP(SEXP zscorexin, SEXP zscoreyin, SEXP Sigmain, SEXP samplen1, SEXP samplen2, SEXP Gibbsnumberin, SEXP burninproportion, SEXP initial_betain, SEXP pi_beta_shape_in, SEXP pi_beta_scale_in, SEXP pi_c_shape_in, SEXP pi_c_scale_in, SEXP pi_1_shape_in, SEXP pi_1_scale_in, SEXP pi_0_shape_in, SEXP pi_0_scale_in, SEXP sigma2x_in, SEXP sigma2y_in, SEXP rho_in);
RcppExport SEXP _MAPLE_MAPLE_CPP(SEXP zscorexinSEXP, SEXP zscoreyinSEXP, SEXP SigmainSEXP, SEXP samplen1SEXP, SEXP samplen2SEXP, SEXP GibbsnumberinSEXP, SEXP burninproportionSEXP, SEXP initial_betainSEXP, SEXP pi_beta_shape_inSEXP, SEXP pi_beta_scale_inSEXP, SEXP pi_c_shape_inSEXP, SEXP pi_c_scale_inSEXP, SEXP pi_1_shape_inSEXP, SEXP pi_1_scale_inSEXP, SEXP pi_0_shape_inSEXP, SEXP pi_0_scale_inSEXP, SEXP sigma2x_inSEXP, SEXP sigma2y_inSEXP, SEXP rho_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type zscorexin(zscorexinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type zscoreyin(zscoreyinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigmain(SigmainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type samplen1(samplen1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type samplen2(samplen2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gibbsnumberin(GibbsnumberinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type burninproportion(burninproportionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial_betain(initial_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_shape_in(pi_beta_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_scale_in(pi_beta_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_c_shape_in(pi_c_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_c_scale_in(pi_c_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_1_shape_in(pi_1_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_1_scale_in(pi_1_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_0_shape_in(pi_0_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_0_scale_in(pi_0_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma2x_in(sigma2x_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma2y_in(sigma2y_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rho_in(rho_inSEXP);
    rcpp_result_gen = Rcpp::wrap(MAPLE_CPP(zscorexin, zscoreyin, Sigmain, samplen1, samplen2, Gibbsnumberin, burninproportion, initial_betain, pi_beta_shape_in, pi_beta_scale_in, pi_c_shape_in, pi_c_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in, sigma2x_in, sigma2y_in, rho_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MAPLE_MAPLE_CPP", (DL_FUNC) &_MAPLE_MAPLE_CPP, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_MAPLE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
